import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from 'playwright'
import { serve } from '../serve.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const shots = join(root, 'test', 'shots')
await mkdir(shots, { recursive: true })
const { server, port } = await serve(root)
const browser = await chromium.launch({ channel: 'chrome', headless: !process.env.HEADED })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', e => { console.error('page error:', e.message); process.exitCode = 1 })
page.on('console', m => { if (m.type() === 'error') console.error('console error:', m.text()) })

let n = 0
const shot = name => page.screenshot({ path: join(shots, `${String(++n).padStart(2, '0')}-${name}.png`) })
const run = (name, input) => page.evaluate(async ([t, i]) => {
  const mc = document.modelContext
  const tool = (await mc.getTools()).find(x => x.name === t)
  if (!tool) return { ok: false, error: 'not registered with the browser: ' + t }
  const out = await mc.executeTool(tool, JSON.stringify(i))
  return typeof out === 'string' ? JSON.parse(out) : out
}, [name, input || {}])
const toolNames = () => page.evaluate(async () => (await document.modelContext.getTools()).map(t => t.name))
const click = id => page.click(`[data-guide="${id}"]`)
const sel = id => `[data-guide="${id}"]`
const plan = (...ids) => ids.map(id => ({ element_id: id, message: `Now ${id.split('.').pop().replace(/-/g, ' ')}.` }))

function start(input) {
  const p = run('run_walkthrough', input)
  p.catch(e => console.error('run_walkthrough rejected:', e.message.split('\n')[0]))
  return p
}

async function act(id, fn) {
  try {
    await page.waitForFunction(id => {
      const s = window.showme.state()
      return s.target === id && s.run && s.run.status === 'in_progress'
    }, id, { timeout: 8000 })
  } catch {
    throw new Error(`no spotlight on ${id}; state=${JSON.stringify(await page.evaluate(() => window.showme.state()))}`)
  }
  await page.waitForTimeout(400)
  await shot(id.replace(/[^a-z0-9]+/gi, '-'))
  try { await fn() } catch (e) { throw new Error(`step ${id}: ${e.message.split('\n')[0]}`) }
}

async function typeEnter(id, text) {
  await page.type(sel(id), text, { delay: 30 })
  await page.press(sel(id), 'Enter')
}

try {
  await page.addInitScript({ path: join(root, 'vendor', 'webmcp-polyfill.js') })
  await page.goto(`http://localhost:${port}/meridian/`)
  await page.waitForFunction(() => window.showme)
  assert.deepEqual(await toolNames(), ['get_ui_map', 'get_current_view', 'run_walkthrough', 'do_step_for_person'])
  assert.match(await page.textContent('.showme-ribbon'), /needs-design/)
  await page.click('.showme-ribbon .close')
  assert.equal(await page.locator('.showme-ribbon').count(), 0)
  await shot('board')

  const map = await run('get_ui_map')
  assert.ok(map.screens.some(s => s.id === 'board-settings'))
  const configure = map.screens.find(s => s.id === 'board').elements.find(e => e.id === 'board.more.configure')
  assert.equal(configure.inside_menu, 'board.more')
  assert.equal(configure.opens, 'board-settings')
  assert.equal(configure.visible, false)
  assert.ok(map.dialogs.some(d => d.id === 'issue' && d.elements.some(e => e.id === 'issue.labels')))

  const bad = await run('run_walkthrough', { steps: plan('board.more', 'nope.nothing') })
  assert.equal(bad.ok, false)
  assert.match(bad.error, /nope\.nothing/)
  const blockedAtStart = await run('run_walkthrough', { steps: plan('board.more.configure') })
  assert.equal(blockedAtStart.status, 'blocked')
  assert.match(blockedAtStart.reason, /board\.more/)
  await run('end_walkthrough')

  let running = start({ steps: plan('board.more', 'board.more.configure', 'boardsettings.tab.columns', 'boardsettings.columns.add', 'boardsettings.columns.name', 'boardsettings.columns.create') })
  await act('board.more', () => click('board.more'))
  assert.ok((await toolNames()).includes('end_walkthrough'))
  await act('board.more.configure', () => click('board.more.configure'))
  await page.click('#agent-activity-btn')
  await page.waitForTimeout(700)
  assert.equal(await page.locator('.agent-drawer .tools li').count(), 5)
  const aligned = await page.evaluate(() => {
    const spot = document.querySelector('.showme-spot')
    const r = document.querySelector('[data-guide="boardsettings.tab.columns"]').getBoundingClientRect()
    return !spot.hidden && Math.abs(parseFloat(spot.style.left) - (r.left - 6)) < 2 && Math.abs(parseFloat(spot.style.top) - (r.top - 6)) < 2
  })
  assert.ok(aligned, 'spotlight follows the Columns tab after the drawer opens')
  const mapBefore = Number(/(\d+) elements/.exec(await page.textContent('.agent-drawer .map'))[1])
  assert.ok(mapBefore > 100, 'map line shows a real element count')
  await shot('drawer')
  await act('boardsettings.tab.columns', () => click('boardsettings.tab.columns'))
  await act('boardsettings.columns.add', () => click('boardsettings.columns.add'))
  await act('boardsettings.columns.name', () => page.type(sel('boardsettings.columns.name'), 'Code Review', { delay: 40 }))
  await act('boardsettings.columns.create', () => page.click('[data-screen="board-settings"] h1'))
  let r = await running
  assert.equal(r.status, 'interrupted')
  assert.equal(r.completed_steps.length, 5)
  assert.match(r.completed_steps[4].action, /Code Review/)
  assert.match(r.reason, /somewhere else.*board-settings/)
  assert.equal(r.now.screen.id, 'board-settings')
  await shot('clicked-elsewhere')

  running = start({ steps: plan('boardsettings.columns.create') })
  await act('boardsettings.columns.create', () => click('boardsettings.columns.create'))
  r = await running
  assert.equal(r.status, 'completed')
  assert.ok(r.now.app_state.board_columns.includes('Code Review'))
  await page.waitForTimeout(600)
  const mapAfter = Number(/(\d+) elements/.exec(await page.textContent('.agent-drawer .map'))[1])
  assert.ok(mapAfter > mapBefore, `map grew after adding a column (${mapBefore} -> ${mapAfter})`)
  await page.click('.agent-drawer .mapdump summary')
  await page.waitForFunction(() => document.querySelector('.agent-drawer .mapdump pre').textContent.length > 100)
  assert.match(await page.textContent('.agent-drawer .mapdump pre'), /"board\.more"/)
  await page.click('.agent-drawer .mapdump summary')
  await shot('column-added')

  const refused = await run('do_step_for_person', { element_id: 'boardsettings.columns.create' })
  assert.equal(refused.refused, true)
  const danger = await run('do_step_for_person', { element_id: 'boardsettings.columns.delete.backlog' })
  assert.equal(danger.refused, true)
  assert.match(danger.reason, /irreversible/)
  const typed = await run('do_step_for_person', { element_id: 'nav.search', value: 'ATL-131' })
  assert.equal(typed.ok, true)
  assert.equal(await page.inputValue('#global-search'), 'ATL-131')
  const navigated = await run('do_step_for_person', { element_id: 'boardsettings.tab.general' })
  assert.equal(navigated.ok, true)
  assert.equal(navigated.now.panel, 'general')

  const chunk = await run('run_walkthrough', { steps: plan('boardsettings.tab.swimlanes'), timeout_seconds: 1 })
  assert.equal(chunk.status, 'in_progress')
  assert.equal(chunk.current_step.element_id, 'boardsettings.tab.swimlanes')
  assert.equal(chunk.current_step.number, 1)
  running = start({})
  await act('boardsettings.tab.swimlanes', () => click('boardsettings.tab.swimlanes'))
  r = await running
  assert.equal(r.status, 'completed')

  const ended = await run('end_walkthrough')
  assert.equal(ended.ok, true)
  assert.ok(!(await toolNames()).includes('end_walkthrough'))
  const nothing = await run('run_walkthrough', {})
  assert.equal(nothing.ok, false)
  await shot('ended')

  await page.click(sel('boardsettings.back'))
  await page.waitForFunction(() => !document.querySelector('[data-screen="board"]').hidden)
  running = start({ title: 'Email all watchers when an issue is assigned', steps: plan('sidebar.project.more', 'sidebar.project.settings', 'projectsettings.tab.notifications', 'projectsettings.notifications.edit.assigned', 'notif.recipient.all-watchers', 'notif.save') })
  await act('sidebar.project.more', () => click('sidebar.project.more'))
  await act('sidebar.project.settings', () => click('sidebar.project.settings'))
  await act('projectsettings.tab.notifications', () => click('projectsettings.tab.notifications'))
  await act('projectsettings.notifications.edit.assigned', () => click('projectsettings.notifications.edit.assigned'))
  await act('notif.recipient.all-watchers', () => page.click('label:has([data-guide="notif.recipient.all-watchers"])'))
  await act('notif.save', () => click('notif.save'))
  r = await running
  assert.equal(r.status, 'completed')
  assert.equal(r.completed_steps[4].action, 'checked')
  assert.ok(r.now.app_state.notification_recipients['Issue assigned'].includes('All watchers'))
  assert.equal(r.learned_path.length, 6)
  assert.ok(r.learned_path.includes('Project settings'))
  await run('end_walkthrough')
  await shot('notifications-saved')

  await page.click(sel('sidebar.filters'))
  await page.waitForFunction(() => !document.querySelector('[data-screen="filters"]').hidden)
  assert.equal((await run('get_current_view')).screen.id, 'filters')
  await page.click(sel('sidebar.board.kanban'))
  await page.waitForFunction(() => !document.querySelector('[data-screen="board"]').hidden)

  const closedDialog = await run('run_walkthrough', { steps: plan('issue.labels') })
  assert.equal(closedDialog.status, 'blocked')
  assert.match(closedDialog.reason, /"issue" dialog/)
  await run('end_walkthrough')

  running = start({ steps: plan('card.ATL-136', 'issue.details', 'issue.labels', 'issue.type', 'issue.type.bug', 'issue.watch', 'issue.watch.add', 'issue.watchers.input', 'issue.close') })
  await act('card.ATL-136', () => click('card.ATL-136'))
  await act('issue.details', () => click('issue.details'))
  await act('issue.labels', () => typeEnter('issue.labels', 'needs-design'))
  await act('issue.type', () => click('issue.type'))
  await act('issue.type.bug', () => click('issue.type.bug'))
  await act('issue.watch', () => click('issue.watch'))
  await act('issue.watch.add', () => click('issue.watch.add'))
  await act('issue.watchers.input', async () => {
    const noLabels = await run('do_step_for_person', { element_id: 'issue.labels', value: 'x' })
    assert.equal(noLabels.refused, true)
    await typeEnter('issue.watchers.input', 'Ana K')
  })
  await act('issue.close', async () => {
    const view = await run('get_current_view')
    assert.ok(view.app_state.open_issue.labels.includes('needs-design'))
    assert.equal(view.app_state.open_issue.type, 'bug')
    assert.ok(view.app_state.open_issue.watchers.includes('Ana K.'))
    await shot('issue-panel')
    await click('issue.close')
  })
  r = await running
  assert.equal(r.status, 'completed')
  assert.equal(r.now.open_dialog, null)
  assert.equal(await page.locator('.card[data-open-issue="ATL-136"] .type.bug').count(), 1)
  assert.equal(await page.locator('.card[data-open-issue="ATL-136"] .chip:has-text("needs-design")').count(), 1)
  await run('end_walkthrough')
  await shot('board-after-issue')

  await page.setViewportSize({ width: 820, height: 900 })
  const drawerOpen = () => page.evaluate(() => !document.querySelector('.agent-drawer').hidden)
  const setDrawer = async open => { if ((await drawerOpen()) !== open) await page.click('#agent-activity-btn') }
  await setDrawer(false)
  await page.goto(`http://localhost:${port}/meridian/#board`)
  await page.reload()
  await page.waitForFunction(() => window.showme)
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  assert.ok(overflow <= 0, `no horizontal page overflow at 820px (got ${overflow})`)
  assert.equal(await page.evaluate(() => document.querySelector('.sidebar').getClientRects().length), 0)
  await shot('narrow-board')
  const closedSidebar = await run('run_walkthrough', { steps: plan('sidebar.project.more') })
  assert.equal(closedSidebar.status, 'blocked')
  assert.match(closedSidebar.reason, /nav\.menu/)
  await run('end_walkthrough')
  await click('nav.menu')
  assert.ok(await page.evaluate(() => document.querySelector('.sidebar').getClientRects().length > 0))
  await shot('narrow-sidebar')
  await click('sidebar.project.more')
  await click('sidebar.project.settings')
  await page.waitForFunction(() => !document.querySelector('[data-screen="project-settings"]').hidden)
  await setDrawer(true)
  await page.waitForTimeout(300)
  await shot('narrow-settings-drawer')
  await setDrawer(false)
  await page.click(sel('nav.menu'))
  await click('sidebar.board.kanban')
  await page.waitForFunction(() => !document.querySelector('[data-screen="board"]').hidden)
  await click('card.ATL-136')
  await page.waitForTimeout(300)
  await shot('narrow-issue')
  await setDrawer(true)
  await page.waitForTimeout(300)
  const modalRight = await page.evaluate(() => document.querySelector('#issue-modal .modal').getBoundingClientRect().right)
  assert.ok(modalRight <= 820 - 340, `issue panel stays clear of the drawer at 820px (right edge ${Math.round(modalRight)})`)
  await shot('narrow-issue-drawer')

  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(`http://localhost:${port}/`)
  await page.waitForFunction(() => window.showme)
  assert.deepEqual(await toolNames(), ['get_ui_map', 'get_current_view', 'run_walkthrough', 'do_step_for_person'])
  assert.match(await page.textContent('.showme-ribbon'), /international transfers/)
  assert.match(await page.getAttribute('.showme-ribbon a', 'href'), /meridian/)
  await shot('bank-ribbon')
  await page.click('.showme-ribbon .close')
  const bank = await run('get_ui_map')
  assert.equal(bank.app, 'Northbank')
  const intl = bank.screens.find(s => s.id === 'settings').elements.find(e => e.id === 'settings.limits.international')
  assert.equal(intl.visible, false)
  assert.ok(!intl.agent_may_do_this)
  assert.ok(bank.dialogs.find(d => d.id === 'confirm-international').elements.find(e => e.id === 'confirm.confirm').irreversible)
  assert.ok((await run('get_current_view')).app_state.recent_transactions.some(t => /AI assistant/.test(t)), 'the planted merchant string reaches the agent only through a result flagged untrusted')
  await shot('bank')

  const closedSection = await run('run_walkthrough', { steps: plan('settings.limits.international') })
  assert.equal(closedSection.status, 'blocked')
  assert.match(closedSection.reason, /"settings" screen/)
  await run('end_walkthrough')

  running = start({ title: 'Turn on international transfers', steps: plan('nav.profile', 'nav.profile.settings', 'settings.tab.limits', 'settings.limits.advanced', 'settings.limits.international', 'confirm.code', 'confirm.confirm') })
  await act('nav.profile', () => click('nav.profile'))
  await act('nav.profile.settings', () => click('nav.profile.settings'))
  await act('settings.tab.limits', () => click('settings.tab.limits'))
  await act('settings.limits.advanced', () => click('settings.limits.advanced'))
  await act('settings.limits.international', () => page.click('label:has([data-guide="settings.limits.international"])'))
  await act('confirm.code', () => page.type(sel('confirm.code'), '482913', { delay: 40 }))
  await act('confirm.confirm', async () => {
    const refused = await run('do_step_for_person', { element_id: 'confirm.confirm' })
    assert.equal(refused.refused, true)
    assert.match(refused.reason, /Northbank policy.*irreversible/)
    await shot('bank-confirm')
    await click('confirm.confirm')
  })
  r = await running
  assert.equal(r.status, 'completed')
  assert.equal(r.now.app_state.international_transfers, 'on')
  assert.equal(r.now.open_dialog, null)
  assert.deepEqual(r.learned_path, ['Profile menu', 'Settings', 'Transfer limits', 'Advanced', 'International transfers', 'Code', 'Confirm'])
  await run('end_walkthrough')
  await page.click('#agent-activity-btn')
  await page.waitForTimeout(400)
  const score = await page.textContent('.agent-drawer .score')
  assert.match(score, /held open \d+s while you acted/)
  assert.match(score, /0 steps delegated, 1 refused by Northbank/)
  assert.match(score, /accepted by this browser: readOnlyHint/)
  assert.match(score, /5 results carried people-typed text/)
  const transcript = await page.textContent('.agent-drawer .calls')
  assert.match(transcript, /Registered 4 tools with document\.modelContext\.registerTool/)
  assert.match(transcript, /Tool added: end_walkthrough/)
  assert.match(transcript, /Tool removed: end_walkthrough/)
  assert.match(transcript, /Northbank refused/)
  assert.ok((await page.locator('.agent-drawer .calls .you li').count()) >= 7, 'the transcript lists what the person did')
  await shot('bank-drawer')
  await page.click('#agent-activity-btn')

  running = start({ title: 'Dispute the double charge at Lumen Coffee', steps: plan('nav.tab.accounts', 'tx.lumen-2', 'tx.more', 'tx.more.dispute', 'tx.dispute.reason', 'tx.dispute.submit') })
  await act('nav.tab.accounts', () => click('nav.tab.accounts'))
  await act('tx.lumen-2', () => click('tx.lumen-2'))
  await act('tx.more', () => click('tx.more'))
  await act('tx.more.dispute', () => click('tx.more.dispute'))
  await act('tx.dispute.reason', () => page.selectOption(sel('tx.dispute.reason'), 'I was charged twice'))
  await act('tx.dispute.submit', async () => {
    const refused = await run('do_step_for_person', { element_id: 'tx.dispute.submit' })
    assert.equal(refused.refused, true)
    assert.match(refused.reason, /person makes themselves/)
    await click('tx.dispute.submit')
  })
  r = await running
  assert.equal(r.status, 'completed')
  assert.equal(r.completed_steps[4].action, 'chose "I was charged twice"')
  assert.equal(r.now.app_state.disputes.length, 1)
  assert.match(r.now.app_state.open_transaction.status, /Disputed/)
  await run('end_walkthrough')
  await shot('bank-disputed')

  const navigated2 = await run('do_step_for_person', { element_id: 'tx.close' })
  assert.equal(navigated2.ok, true)
  assert.equal(navigated2.now.open_dialog, null)
  const freeze = await run('do_step_for_person', { element_id: 'cards.debit.freeze' })
  assert.equal(freeze.refused, true)

  console.log(`PASS  ${n} screenshots in test/shots`)
} finally {
  await browser.close()
  server.close()
}
